### ISSUE TITLE
Change secretTokenQueryParam

### ISSUE THREAD

**Issue by multiplehats** [darbymanning/sveltekit-preview-mode#11]
Hey there!

Thanks for creating this package. I was about to create it myself and figured I would do one more search because when I searched weeks ago, I couldn't find anything.

Would you agree that changing the default `secret` secretTokenQueryParam to `preview` is more inline with this package? So to enter the preview, you need to `?preview=SECRET` and to exit append `?exit-preview` or even `?preview-exit`.

Eager to hear your thoughts.

**Comment by darbymanning** [comment]
Nice 👌

Certainly happy with those defaults. I’m not tightly weld to any of it, agree that those sound sensible. Bit overloaded at the moment (half term childcare chaos) but looking to do a lot of work on this shortly, so will look to implement that change as part of it. 


Thanks!

**Comment by darbymanning** [comment]
Clearly I never recovered from that childcare chaos.

In any case, due to my tardiness and the package being adopted a bit more now - I think we should avoid a breaking change here, so it may just be best to set this using the options:

https://github.com/darbymanning/sveltekit-preview-mode#options

So in your case you'd just do:

```ts
export const handle: Handle = previewMode({
  previewSecret: PREVIEW_SECRET,
  secretTokenQueryParam: "preview",
});
```

Then appending query param `exit-preview` will exit, or you can customise that string with `exitPreviewQueryParam`.

Let me know if you encounter any issues with that, sorry I missed the boat on this one!
